#
# Copyright 2013 Ettus Research LLC
#

##################################################
# VITA Sources
##################################################
VITA_SRCS = $(abspath $(addprefix $(BASE_DIR)/../lib/vita/, \
flow_control_responder.v \
packet_error_responder.v \
))
